AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'tmp/**/*'
  UseCache: true
  CacheRootDirectory: ./tmp
  # TODO: Style/RedundantBegin の調整が済み次第 2.5 に更新する。
  TargetRubyVersion: 2.5

# rspec の `expect { hoge }` などが対象となり邪魔なので無効にする。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/AmbiguousBlockAssociation
#
Lint/AmbiguousBlockAssociation:
  Enabled: false

# true と比較することなんてないし `return unless x = exp` な感じで条件式でも代入したいので無効にする。
#
# `AllowSafeAssignment: true` を設定すれば `if (x = 10)` を受け入れてくれる様だけど、読みやすい気がしないしやめておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/AssignmentInCondition
#
Lint/AssignmentInCondition:
  Enabled: false

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/AbcSize
#
Metrics/AbcSize:
  Max: 30

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/BlockNesting
#
Metrics/BlockNesting:
  Max: 3

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/ClassLength
#
Metrics/ClassLength:
  CountComments: false
  Max: 400

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/ModuleLength
#
Metrics/ModuleLength:
  CountComments: false
  Max: 300

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/CyclomaticComplexity
#
Metrics/CyclomaticComplexity:
  Max: 6

# 128 文字程度にしておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/LineLength
#
Metrics/LineLength:
  Max: 128
  AllowURI: true
  URISchemes:
    - http
    - https

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/MethodLength
#
Metrics/MethodLength:
  CountComments: false
  Max: 20

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/ParameterLists
#
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/PerceivedComplexity
#
Metrics/PerceivedComplexity:
  Max: 7


# ヒアドキュメントのデリミタは自由で良い気がするので無効にする。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/HeredocDelimiterNaming
#
Naming/HeredocDelimiterNaming:
  Enabled: false

# 強制する必要はないと考えて無効に。
#
# @see https://rubocop.readthedocs.io/en/latest/cops_naming/#namingmemoizedinstancevariablename
#
Naming/MemoizedInstanceVariableName:
  Enabled: false

# 現状追認
#
# @see https://rubocop.readthedocs.io/en/latest/cops_naming/#naminguncommunicativemethodparamname
#
Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

# 主にテストコードで使う連番変数。棚上げするため無効にしておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/VariableNumber
#
Naming/VariableNumber:
  Enabled: false

# 日本語を使いたいので無効にする。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/AsciiComments
#
Style/AsciiComments:
  Enabled: false

# 基本的にブロックコメントは不要だと思うけど、rspec のジェネレータで作ったファイルには含まれている。これだけは許可しておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/BlockComments
#
Style/BlockComments:
  Exclude:
    - 'codedeploy/spec/spec_helper.rb'
    - 'spec/spec_helper.rb'

# 良い感じに。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/BracesAroundHashParameters
#
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
  SupportedStyles:
    - braces
    - no_braces
    - context_dependent

# ドキュメンテーションは強制したい気持ちが出てきているけど、歴史的経緯もあるので Rubocop での強制は行わない。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/Documentation
#
Style/Documentation:
  Enabled: false

# `!!` は使いたいので無効にする。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/DoubleNegation
#
Style/DoubleNegation:
  Enabled: false

# 空 case は使いたいので無効にする。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyCaseCondition
#
Style/EmptyCaseCondition:
  Enabled: false

# `else` 節で `nil` を返す際は明確に `nil` と書きたいので empty スタイルを採用。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyElse
#
Style/EmptyElse:
  EnforcedStyle: empty

# expanded スタイルにしておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyMethod
#
Style/EmptyMethod:
  EnforcedStyle: expanded


# 現状追認。
#
# @see https://rubocop.readthedocs.io/en/latest/cops_style/#styleexpandpatharguments
#
Style/ExpandPathArguments:
  Enabled: false

# annotated スタイルが明示的で良さそうな気がしつつ、そこまで書き方を限定すべきか悩んだので unannotated にしておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FormatStringToken
#
Style/FormatStringToken:
  EnforcedStyle: unannotated

# 棚上げ中。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment
#
Style/FrozenStringLiteralComment:
  Enabled: false

# 使うとしたら歴史的経緯から comparison スタイルな気がするけど、気にしなくても分かりやすい気がするので無効にしておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/NumericPredicate
#
Style/NumericPredicate:
  Enabled: false

# 統一書式となるように設定しておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/PercentLiteralDelimiters
#
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RescueStandardError
#
Style/RescueStandardError:
  EnforcedStyle: implicit

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SignalException
#
Style/SignalException:
  EnforcedStyle: semantic

# 統一するなら brackets スタイルが修正範囲が狭そうだけど、無理に揃えなくても分かりやすいかなと思ったので無効にしておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SymbolArray
Style/SymbolArray:
  Enabled: false
  # EnforcedStyle: brackets

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TernaryParentheses
#
Style/TernaryParentheses:
  Enabled: false

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingCommaInArguments
#
Style/TrailingCommaInArguments:
  Enabled: false

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingCommaInLiteral
#
Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

##################### Rails ##################################

Rails:
  Enabled: true
  Exclude:
    - 'bin/continuous_bundle_update.rb'

# 現状追認。
#
# @see http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Rails/ActionFilter
#
Rails/ActionFilter:
  EnforcedStyle: action
  Include:
    - app/controllers/**/*.rb

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/Date
#
Rails/Date:
  EnforcedStyle: flexible

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/FindBy
#
Rails/FindBy:
  Include:
    - app/models/**/*.rb

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/FindEach
#
Rails/FindEach:
  Include:
    - app/models/**/*.rb

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/HasAndBelongsToMany
#
Rails/HasAndBelongsToMany:
  Include:
    - app/models/**/*.rb

# やんごとなき理由から dependent を付けない事があるので無効にしておく。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/HasManyOrHasOneDependent
#
Rails/HasManyOrHasOneDependent:
  Enabled: false

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/Output
#
Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/ReadWriteAttribute
#
Rails/ReadWriteAttribute:
  Include:
    - app/models/**/*.rb

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/ScopeArgs
#
Rails/ScopeArgs:
  Include:
    - app/models/**/*.rb

# やんごとなき理由からバリデーションを回避することはよくあるので無効にする。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/SkipsModelValidations
#
Rails/SkipsModelValidations:
  Enabled: false

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/TimeZone
#
Rails/TimeZone:
  EnforcedStyle: flexible

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/Validation
#
Rails/Validation:
  Include:
    - app/models/**/*.rb

# 現状追認。
#
# @see http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/HttpStatus
#
Rails/HttpStatus:
  EnforcedStyle: numeric
